version: "3.8"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector-db
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password # erm for sure don't deploy in prod
      POSTGRES_DB: db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d # this auto-runs *.sql files at startup

volumes:
  pgdata:
